using Tabulo.Generator.Parsers;

namespace Tabulo.Generator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;
using System.Linq;

[Generator]
public class CsvSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(
            compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

            if (symbol == null)
                continue;

            var attrData = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "CsvRecordAttribute");

            if (attrData == null)
                continue;

            char delimiter = ',';

            foreach (var arg in attrData.NamedArguments)
            {
                if (arg.Key == "Delimiter" &&
                    arg.Value.Value is char c)
                {
                    delimiter = c;
                }
            }

            var className = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            var properties = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Select(p =>
                {
                    var nullableType = p.Type as INamedTypeSymbol;

                    bool isNullable =
                        nullableType?.ConstructedFrom?.ToDisplayString() ==
                        "System.Nullable<T>";

                    string underlyingType =
                        isNullable
                            ? nullableType!.TypeArguments[0].ToDisplayString()
                            : p.Type.ToDisplayString();

                    return new CsvProperty
                    {
                        Name = p.Name,
                        Type = p.Type.ToDisplayString(),
                        ColumnName = GetColumnName(p),
                        IsNullable = isNullable,
                        UnderlyingType = underlyingType
                    };
                })
                .ToList();

            var source = GenerateParser(
                namespaceName,
                className,
                delimiter,
                properties);

            context.AddSource($"{className}CsvParser.g.cs", source);
        }
    }

    static string? GetColumnName(IPropertySymbol property)
    {
        var attr = property.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "CsvColumnAttribute");

        if (attr != null &&
            attr.ConstructorArguments.Length > 0)
        {
            return attr.ConstructorArguments[0].Value as string;
        }

        return property.Name;
    }

    private static string GenerateParser(
        string namespaceName,
        string className,
        char delimiter,
        List<CsvProperty> props)
    {
        var sb = new StringBuilder();

        sb.AppendLine($@"
// <auto-generated>

using System;
using System.IO;
using System.Collections.Generic;
using System.Threading;
using Tabulo;

namespace {namespaceName}
{{
    public partial class {className} : ICsvParser<{className}>
    {{
");

        foreach (var p in props)
        {
            sb.AppendLine($"        private int _idx_{p.Name} = -1;");
        }

        sb.AppendLine($@"

        public bool TryParseLine(ReadOnlySpan<char> line, out {className} result)
        {{
            Span<Range> ranges = stackalloc Range[Math.Max({props.Count} + 8, 32)];

            int count = Split(line, ranges);

            result = new {className}();

");
        
        foreach (var p in props)
        {
            sb.AppendLine($@"
            if (_idx_{p.Name} < 0 || _idx_{p.Name} >= count)
                return false;
");
        }

        foreach (var p in props)
        {
            string spanAccess =
                $"UnwrapQuoted(line[ranges[_idx_{p.Name}]])";

            string code = GeneratePropertyParser(
                p,
                spanAccess);

            sb.AppendLine(code);
        }

        sb.AppendLine(@"

            return true;
        }");

        sb.AppendLine($@"

        public IEnumerable<{className}> ParseStream(
            TextReader reader,
            bool skipInvalid = true,
            Action<string>? onError = null)
        {{
            var header = reader.ReadLine();

            if (header == null)
                yield break;

            var span = header.AsSpan();

            Span<Range> ranges = stackalloc Range[Math.Max({props.Count} + 8, 32)];

            int count = Split(span, ranges);

");

        foreach (var p in props)
        {
            sb.AppendLine($@"
            for (int i = 0; i < count; i++)
            {{
                var col = UnwrapQuoted(span[ranges[i]]).Trim();

                if (col.SequenceEqual(""{p.ColumnName}"".AsSpan()))
                {{
                    _idx_{p.Name} = i;
                    break;
                }}
            }}

            if (_idx_{p.Name} == -1)
                throw new InvalidOperationException(""Required column not found: {p.ColumnName}"");

");
        }

        sb.AppendLine(@"

            string? line;

            while ((line = reader.ReadLine()) != null)
            {
                var lineSpan = line.AsSpan();

                if (TryParseLine(lineSpan, out var item))
                {
                    yield return item;
                }
                else
                {
                    onError?.Invoke(line);

                    if (!skipInvalid)
                        throw new FormatException($""Invalid CSV line: '{line}'"");
                }
            }
        }");

        sb.AppendLine($@"

        public async IAsyncEnumerable<{className}> ParseStreamAsync(
            TextReader reader,
            bool skipInvalid = true,
            Action<string>? onError = null,
            [System.Runtime.CompilerServices.EnumeratorCancellation]
            CancellationToken ct = default)
        {{
            var header = await reader.ReadLineAsync().ConfigureAwait(false);

            if (header == null)
                yield break;

            var span = header.AsSpan();

            var rangesArray = new Range[Math.Max({props.Count} + 8, 32)];

            Span<Range> ranges = rangesArray;

            int count = Split(span, ranges);

");

        foreach (var p in props)
        {
            sb.AppendLine($@"
            for (int i = 0; i < count; i++)
            {{
                var col = UnwrapQuoted(span[ranges[i]]).Trim();

                if (col.SequenceEqual(""{p.ColumnName}"".AsSpan()))
                {{
                    _idx_{p.Name} = i;
                    break;
                }}
            }}

            if (_idx_{p.Name} == -1)
                throw new InvalidOperationException(""Required column not found: {p.ColumnName}"");

");
        }

        sb.AppendLine(@"

            string? line;

            while ((line = await reader.ReadLineAsync().ConfigureAwait(false)) != null)
            {
                ct.ThrowIfCancellationRequested();

                var lineSpan = line.AsSpan();

                if (TryParseLine(lineSpan, out var item))
                {
                    yield return item;
                }
                else
                {
                    onError?.Invoke(line);

                    if (!skipInvalid)
                        throw new FormatException($""Invalid CSV line: '{line}'"");
                }
            }
        }");

        sb.AppendLine($@"

        private static ReadOnlySpan<char> UnwrapQuoted(ReadOnlySpan<char> value)
        {{
            value = value.Trim();

            if (value.Length >= 2 &&
                value[0] == '""' &&
                value[^1] == '""')
            {{
                return value[1..^1];
            }}

            return value;
        }}
");
        
        sb.AppendLine(@"

        private static bool IsEmpty(ReadOnlySpan<char> value)
        {
            return value.Trim().IsEmpty;
        }
");

        sb.AppendLine($@"

        private static int Split(ReadOnlySpan<char> line, Span<Range> ranges)
        {{
            int count = 0;
            int start = 0;

            bool inQuotes = false;

            for (int i = 0; i < line.Length; i++)
            {{
                char c = line[i];

                if (c == '""')
                {{
                    // Escaped quote ("")
                    if (inQuotes &&
                        i + 1 < line.Length &&
                        line[i + 1] == '""')
                    {{
                        i++;
                        continue;
                    }}

                    inQuotes = !inQuotes;
                    continue;
                }}

                if (c == '{delimiter}' && !inQuotes)
                {{
                    ranges[count++] = start..i;
                    start = i + 1;
                }}
            }}

            ranges[count++] = start..line.Length;

            return count;
        }}
");

        sb.AppendLine(IntParser.GenerateParserCode());
        sb.AppendLine(LongParser.GenerateParserCode());
        sb.AppendLine(DecimalParser.GenerateParserCode());
        sb.AppendLine(DateTimeParser.GenerateParserCode());
        sb.AppendLine(BoolParser.GenerateParseCode());
        sb.AppendLine(DoubleParser.GenerateParseCode());

        sb.AppendLine(@"
    }
}");

        return sb.ToString();
    }
    
    private static string GeneratePropertyParser(
        CsvProperty p,
        string spanAccess)
    {
        if (p.IsNullable)
        {
            return GenerateNullableParser(
                p,
                spanAccess);
        }

        return p.UnderlyingType switch
        {
            "int" => $@"
            if (!TryParseInt({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            "long" => $@"
            if (!TryParseLong({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            "decimal" => $@"
            if (!TryParseDecimal({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            "double" => $@"
            if (!TryParseDouble({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            "bool" => $@"
            if (!TryParseBool({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            "DateTime" or "System.DateTime" => $@"
            if (!TryParseDateTime({spanAccess}, out var __{p.Name}))
                return false;

            result.{p.Name} = __{p.Name};",

            _ => $@"
            result.{p.Name} = {spanAccess}.ToString();"
        };
    }
    
    private static string GenerateNullableParser(
        CsvProperty p,
        string spanAccess)
    {
        string parserMethod = p.UnderlyingType switch
        {
            "int" => "TryParseInt",
            "long" => "TryParseLong",
            "decimal" => "TryParseDecimal",
            "double" => "TryParseDouble",
            "bool" => "TryParseBool",
            "DateTime" or "System.DateTime" => "TryParseDateTime",
            _ => string.Empty
        };

        if (string.IsNullOrWhiteSpace(parserMethod))
        {
            return $@"
            result.{p.Name} =
                IsEmpty({spanAccess})
                    ? null
                    : {spanAccess}.ToString();";
        }

        return $@"
            if (IsEmpty({spanAccess}))
            {{
                result.{p.Name} = null;
            }}
            else
            {{
                if (!{parserMethod}({spanAccess}, out var __{p.Name}))
                    return false;

                result.{p.Name} = __{p.Name};
            }}";
    }
}