using Tabulo.Generator.Parsers;

namespace Tabulo.Generator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;
using System.Linq;

[Generator]
public class CsvSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

            if (symbol == null)
                continue;
            
            var attrData = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "CsvRecordAttribute");

            if (attrData == null)
                continue;

            char delimiter = ',';

            foreach (var arg in attrData.NamedArguments)
            {
                if (arg.Key == "Delimiter" && arg.Value.Value is char c)
                {
                    delimiter = c;
                }
            }

            var className = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            var properties = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Select(p => new CsvProperty
                {
                    Name = p.Name,
                    Type = p.Type.ToDisplayString(),
                    ColumnName = GetColumnName(p)
                })
                .ToList();

            var source = GenerateParser(namespaceName, className, delimiter, properties);

            context.AddSource($"{className}CsvParser.g.cs", source);
        }
    }

    static string? GetColumnName(IPropertySymbol property)
    {
        var attr = property.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "CsvColumnAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0)
        {
            return attr.ConstructorArguments[0].Value as string;
        }
        return property.Name;
    }

   private static string GenerateParser(string namespaceName, string className, char delimiter, List<CsvProperty> props)
{
    var sb = new StringBuilder();
    
    sb.AppendLine($@"
// <auto-generated>
using System;
using System.IO;
using System.Collections.Generic;
using Tabulo;

namespace {namespaceName}
{{
    public partial class {className} : ICsvParser<{className}>
    {{
");
    
    foreach (var p in props)
    {
        sb.AppendLine($"        private int _idx_{p.Name};");
    }

    sb.AppendLine($@"
        public bool TryParseLine(ReadOnlySpan<char> line, out {className} result)
        {{
            Span<Range> ranges = stackalloc Range[{props.Count + 4}];
            int count = Split(line, ranges);

            result = new {className}();
");

    foreach (var p in props)
    {
        string spanAccess = $"line[ranges[_idx_{p.Name}]]";

        string code = p.Type switch
        {
            "int" => $@"
            if (!TryParseInt({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            "long" => $@"
            if (!TryParseLong({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            "decimal" => $@"
            if (!TryParseDecimal({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            "double" => $@"
            if (!TryParseDouble({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            "DateTime" or "System.DateTime" => $@"
            if (!TryParseDateTime({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            "bool" => $@"
            if (!TryParseBool({spanAccess}, out var __{p.Name}))
                return false;
            result.{p.Name} = __{p.Name};",

            _ => $@"
            result.{p.Name} = {spanAccess}.ToString();"
        };

        sb.AppendLine(code);
    }

    sb.AppendLine(@"
            return true;
        }");

    sb.AppendLine($@"
        public IEnumerable<{className}> ParseStream(TextReader reader, bool skipInvalid = true, Action<string>? onError = null)
        {{
            var header = reader.ReadLine();
            if (header == null) yield break;

            var span = header.AsSpan();
            Span<Range> ranges = stackalloc Range[{props.Count + 4}];
            int count = Split(span, ranges);

            for (int i = 0; i < count; i++)
            {{
                var col = span[ranges[i]].Trim();

");

    foreach (var p in props)
    {
        sb.AppendLine($@"
                if (col.SequenceEqual(""{p.ColumnName}"".AsSpan()))
                    _idx_{p.Name} = i;");
    }

    sb.AppendLine(@"
            }

            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                var lineSpan = line.AsSpan();
                if (TryParseLine(lineSpan, out var item))
                {
                    yield return item;
                }
                else
                {
                    // Error handling
                    onError?.Invoke(line);
                    if (!skipInvalid)
                        throw new FormatException($""Invalid CSV line: '{line}'"");
                    // else skip line
                }
            }
        }");
    
    sb.AppendLine($@"
        public async IAsyncEnumerable<{className}> ParseStreamAsync(
            TextReader reader,
            bool skipInvalid = true,
            Action<string>? onError = null,
            [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct = default)
        {{
            var header = await reader.ReadLineAsync().ConfigureAwait(false);
            if (header == null) yield break;

            var span = header.AsSpan();
            var rangesArray = new Range[{props.Count + 4}];
            Span<Range> ranges = rangesArray;
            int count = Split(span, ranges);
");

    foreach (var p in props)
    {
        sb.AppendLine($@"
            for (int i = 0; i < count; i++)
            {{
                var col = span[ranges[i]].Trim();
                if (col.SequenceEqual(""{p.ColumnName}"".AsSpan()))
                    _idx_{p.Name} = i;
            }}");
    }

    sb.AppendLine(@"
            string? line;
            while ((line = await reader.ReadLineAsync().ConfigureAwait(false)) != null)
            {
                ct.ThrowIfCancellationRequested();

                var lineSpan = line.AsSpan();
                if (TryParseLine(lineSpan, out var item))
                {
                    yield return item;
                }
                else
                {
                    if (onError != null)
                        onError(line);

                    if (!skipInvalid)
                        throw new FormatException($""Invalid CSV line: '{line}'"");
                }
            }
        }");

    sb.AppendLine($@"
        private static int Split(ReadOnlySpan<char> line, Span<Range> ranges)
        {{
            int count = 0;
            int start = 0;

            for (int i = 0; i < line.Length; i++)
            {{
                if (line[i] == '{delimiter}')
                {{
                    ranges[count++] = start..i;
                    start = i + 1;
                }}
            }}

            ranges[count++] = start..line.Length;
            return count;
        }}");

    sb.AppendLine(IntParser.GenerateParserCode());
    sb.AppendLine(LongParser.GenerateParserCode());
    sb.AppendLine(DecimalParser.GenerateParserCode());
    sb.AppendLine(DateTimeParser.GenerateParserCode());
    sb.AppendLine(BoolParser.GenerateParseCode());
    sb.AppendLine(DoubleParser.GenerateParseCode());

    sb.AppendLine(@"
    }
}");

    return sb.ToString();
}
}