name: .NET Build

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Tabulo/Tabulo.sln

      - name: Build
        run: dotnet build Tabulo/Tabulo.sln --no-restore --verbosity minimal

      - name: Test
        run: dotnet test Tabulo/Tabulo.sln --no-build --verbosity normal
